In [18]:
import numpy as np
import pandas as pd
from scipy.stats import pearsonr
import seaborn as sn
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv('DataSetPrimer.csv')
df.index = df.id
df = df.drop(['id', 'action', 'video_src'], axis = 1)
df

,Nose_x0,Nose_y0,Neck_x1,Neck_y1,RShoulder_x2,RShoulder_y2,Relbow_x3,RElbow_y3,RWrist_x4,RWrist_y4,...,LAnkle_x13,LAnkle_y13,REye_x14,REye_y14,LEye_x15,LEye_y15,REar_x16,REar_y16,LEar_x17,LEar_y17
id,,,,,,,,,,,,,,,,,,,,,
990,150,20,157,29,156,28,153.0,40.0,147.0,51.0,...,NaN,NaN,NaN,NaN,152,18,NaN,NaN,156,18
991,148,20,156,29,156,27,151.0,42.0,NaN,NaN,...,139.0,95.0,NaN,NaN,150,18,NaN,NaN,154,20
992,145,19,153,29,153,27,NaN,NaN,NaN,NaN,...,139.0,96.0,NaN,NaN,147,18,NaN,NaN,151,19
993,143,19,150,29,149,28,144.0,44.0,NaN,NaN,...,138.0,96.0,NaN,NaN,144,18,NaN,NaN,149,18
994,140,18,147,28,147,27,140.0,42.0,NaN,NaN,...,138.0,97.0,NaN,NaN,141,17,NaN,NaN,147,18
995,138,18,146,27,144,26,NaN,NaN,NaN,NaN,...,138.0,97.0,NaN,NaN,139,16,NaN,NaN,144,18
996,135,18,143,27,141,25,NaN,NaN,NaN,NaN,...,139.0,95.0,NaN,NaN,136,16,NaN,NaN,141,17
997,133,16,141,27,139,25,NaN,NaN,NaN,NaN,...,138.0,95.0,NaN,NaN,134,15,NaN,NaN,139,16
998,130,17,138,27,138,25,NaN,NaN,NaN,NaN,...,138.0,95.0,NaN,NaN,132,15,NaN,NaN,136,16
999,127,17,135,27,134,25,129.0,42.0,123.0,48.0,...,138.0,95.0,NaN,NaN,129,16,NaN,NaN,133,17

In [20]:
A = np.array(df.fillna(0).values).T
A

array([[150., 148., 145., 143., 140., 138., 135., 133., 130., 127.],
       [ 20.,  20.,  19.,  19.,  18.,  18.,  18.,  16.,  17.,  17.],
       [157., 156., 153., 150., 147., 146., 143., 141., 138., 135.],
       [ 29.,  29.,  29.,  29.,  28.,  27.,  27.,  27.,  27.,  27.],
       [156., 156., 153., 149., 147., 144., 141., 139., 138., 134.],
       [ 28.,  27.,  27.,  28.,  27.,  26.,  25.,  25.,  25.,  25.],
       [153., 151.,   0., 144., 140.,   0.,   0.,   0.,   0., 129.],
       [ 40.,  42.,   0.,  44.,  42.,   0.,   0.,   0.,   0.,  42.],
       [147.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 123.],
       [ 51.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  48.],
       [  0., 156., 154., 151., 149., 147., 144., 141., 139., 136.],
       [  0.,  29.,  29.,  29.,  29.,  28.,  28.,  28.,  28.,  28.],
       [  0., 152., 150., 150., 143., 141., 141., 136., 133., 131.],
       [  0.,  43.,  44.,  46.,  44.,  44.,  44.,  42.,  44.,  42.],
       [  0., 148., 148., 150.,   0.,   0.,   0., 130., 125., 121.],
       [  0.,  53.,  57.,  59.,   0.,   0.,   0.,  52.,  50.,  48.],
       [152., 150., 148., 144., 143., 140., 137., 135., 134., 130.],
       [ 60.,  58.,  57.,  57.,  55.,  57.,  54.,  53.,  55.,  56.],
       [145., 143., 153., 147., 143., 139., 135., 131., 125., 134.],
       [ 77.,  76.,  75.,  75.,  75.,  76.,  74.,  72.,  70.,  74.],
       [140., 138.,   0.,   0.,   0., 152., 139., 136., 130., 137.],
       [ 95.,  96.,   0.,   0.,   0.,  88.,  94.,  95.,  92.,  94.],
       [155., 153., 149., 146., 144., 141., 140., 136., 133., 132.],
       [ 59.,  58.,  57.,  57.,  55.,  57.,  55.,  53.,  55.,  56.],
       [  0., 142., 140., 139., 137., 136., 136., 133., 135., 133.],
       [  0.,  76.,  76.,  75.,  76.,  76.,  74.,  73.,  75.,  74.],
       [  0., 139., 139., 138., 138., 138., 139., 138., 138., 138.],
       [  0.,  95.,  96.,  96.,  97.,  97.,  95.,  95.,  95.,  95.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [152., 150., 147., 144., 141., 139., 136., 134., 132., 129.],
       [ 18.,  18.,  18.,  18.,  17.,  16.,  16.,  15.,  15.,  16.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [156., 154., 151., 149., 147., 144., 141., 139., 136., 133.],
       [ 18.,  20.,  19.,  18.,  18.,  18.,  17.,  16.,  16.,  17.]])

In [26]:
from sklearn.decomposition import PCA
pca_breast = PCA(n_components=2)
principalComponents_breast = pca_breast.fit_transform(A)

In [29]:
principalComponents_breast.T

array([[ 210.86249815, -167.72422228,  235.10548558, -137.24166503,
         232.31008043, -142.31806463,  -11.64320848, -162.04843422,
        -159.65240719, -200.70323046,  204.44896101, -141.47388491,
         191.50280317,  -96.88002947,   41.89442883, -121.44934467,
         218.38980163,  -48.73631935,  213.14726562,    8.56024117,
          72.77861718,  -24.8743844 ,  223.27641838,  -48.61798937,
         175.91917834,   -5.16381792,  180.14167477,   55.26513263,
        -224.76559645, -224.76559645,  215.4972363 , -172.40456212,
        -224.76559645, -224.76559645,  230.01719639, -169.12306926],
       [  40.72270759,   -8.53196652,   42.82347477,   -6.02832809,
          42.18410596,   -5.99888957,  122.70691693,   20.17546173,
         137.19128534,   37.63507569, -100.57963978,  -32.5635684 ,
         -98.54838044,  -41.40101573,  -93.29782059,  -46.67497989,
          41.16232816,    7.11759107,   35.1154338 ,   12.8172019 ,
          99.36946842,   61.47757066,   43.64212705,    6.19479393,
         -93.56535559,  -58.40373879,  -93.48299598,  -69.80811099,
         -16.57623896,  -16.57623896,   41.74385704,   -9.67143129,
         -16.57623896,  -16.57623896,   42.83504374,  -10.05326629]])

In [30]:
print('Explained variation per principal component: {}'.format(pca_breast.explained_variance_ratio_))

Explained variation per principal component: [0.79212652 0.09653701]