In [46]:
from sklearn.decomposition import LatentDirichletAllocation as LDA
import numpy as np
import pandas as pd
import gensim
from sklearn.externals import joblib


import numpy as np
import pandas as pd
import re, nltk, spacy, gensim

# Sklearn
from sklearn.decomposition import LatentDirichletAllocation, TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import GridSearchCV
from pprint import pprint

# Plotting tools
import pyLDAvis
import pyLDAvis.sklearn
import matplotlib.pyplot as plt
%matplotlib inline

In [47]:
df = pd.read_csv('DataSetPrimer.csv')
df.index = df.id
df = df.drop(['id', 'action', 'video_src'], axis = 1)
df = df.fillna(0)
df

,Nose_x0,Nose_y0,Neck_x1,Neck_y1,RShoulder_x2,RShoulder_y2,Relbow_x3,RElbow_y3,RWrist_x4,RWrist_y4,...,LAnkle_x13,LAnkle_y13,REye_x14,REye_y14,LEye_x15,LEye_y15,REar_x16,REar_y16,LEar_x17,LEar_y17
id,,,,,,,,,,,,,,,,,,,,,
990,150,20,157,29,156,28,153.0,40.0,147.0,51.0,...,0.0,0.0,0.0,0.0,152,18,0.0,0.0,156,18
991,148,20,156,29,156,27,151.0,42.0,0.0,0.0,...,139.0,95.0,0.0,0.0,150,18,0.0,0.0,154,20
992,145,19,153,29,153,27,0.0,0.0,0.0,0.0,...,139.0,96.0,0.0,0.0,147,18,0.0,0.0,151,19
993,143,19,150,29,149,28,144.0,44.0,0.0,0.0,...,138.0,96.0,0.0,0.0,144,18,0.0,0.0,149,18
994,140,18,147,28,147,27,140.0,42.0,0.0,0.0,...,138.0,97.0,0.0,0.0,141,17,0.0,0.0,147,18
995,138,18,146,27,144,26,0.0,0.0,0.0,0.0,...,138.0,97.0,0.0,0.0,139,16,0.0,0.0,144,18
996,135,18,143,27,141,25,0.0,0.0,0.0,0.0,...,139.0,95.0,0.0,0.0,136,16,0.0,0.0,141,17
997,133,16,141,27,139,25,0.0,0.0,0.0,0.0,...,138.0,95.0,0.0,0.0,134,15,0.0,0.0,139,16
998,130,17,138,27,138,25,0.0,0.0,0.0,0.0,...,138.0,95.0,0.0,0.0,132,15,0.0,0.0,136,16
999,127,17,135,27,134,25,129.0,42.0,123.0,48.0,...,138.0,95.0,0.0,0.0,129,16,0.0,0.0,133,17

In [48]:
A = df.values
A[:1]

array([[150.,  20., 157.,  29., 156.,  28., 153.,  40., 147.,  51.,   0.,
          0.,   0.,   0.,   0.,   0., 152.,  60., 145.,  77., 140.,  95.,
        155.,  59.,   0.,   0.,   0.,   0.,   0.,   0., 152.,  18.,   0.,
          0., 156.,  18.]])

In [61]:
lda = LDA(n_components = 5,
                 max_iter=30,
                 n_jobs=6,
                 learning_method='batch',
                 verbose=1)

lda_output = lda.fit_transform(A)

iteration: 1 of max_iter: 30
iteration: 2 of max_iter: 30
iteration: 3 of max_iter: 30
iteration: 4 of max_iter: 30
iteration: 5 of max_iter: 30
iteration: 6 of max_iter: 30
iteration: 7 of max_iter: 30
iteration: 8 of max_iter: 30
iteration: 9 of max_iter: 30
iteration: 10 of max_iter: 30
iteration: 11 of max_iter: 30
iteration: 12 of max_iter: 30
iteration: 13 of max_iter: 30
iteration: 14 of max_iter: 30
iteration: 15 of max_iter: 30
iteration: 16 of max_iter: 30
iteration: 17 of max_iter: 30
iteration: 18 of max_iter: 30
iteration: 19 of max_iter: 30
iteration: 20 of max_iter: 30
iteration: 21 of max_iter: 30
iteration: 22 of max_iter: 30
iteration: 23 of max_iter: 30
iteration: 24 of max_iter: 30
iteration: 25 of max_iter: 30
iteration: 26 of max_iter: 30
iteration: 27 of max_iter: 30
iteration: 28 of max_iter: 30
iteration: 29 of max_iter: 30
iteration: 30 of max_iter: 30

In [62]:
lda_output

array([[9.40912012e-05, 9.44926666e-05, 9.38853836e-05, 9.99623019e-01,
        9.45113707e-05],
       [1.85257477e-01, 2.89052620e-01, 2.61023934e-01, 6.90278651e-05,
        2.64596941e-01],
       [9.99676027e-01, 8.10523482e-05, 8.05217101e-05, 8.05479512e-05,
        8.18509519e-05],
       [4.78149082e-01, 7.60093958e-05, 7.61725974e-05, 7.58328123e-05,
        5.21622903e-01],
       [8.40465784e-05, 8.41668353e-05, 8.35766239e-05, 8.36893142e-05,
        9.99664521e-01],
       [8.29180406e-05, 9.99668833e-01, 8.24909958e-05, 8.26493053e-05,
        8.31085683e-05],
       [8.44571548e-05, 9.99662765e-01, 8.40249673e-05, 8.41702455e-05,
        8.45827612e-05],
       [4.25379866e-01, 5.74380428e-01, 8.00887867e-05, 7.97204965e-05,
        7.98969748e-05],
       [4.24741310e-01, 5.75015774e-01, 8.11546959e-05, 8.07810910e-05,
        8.09805722e-05],
       [1.82549560e-01, 1.43336527e-01, 2.94340009e-01, 3.13911760e-01,
        6.58621439e-02]])

In [63]:
lda.score(A)

-81263.67600583695

In [64]:
lda.perplexity(A)

23.743531370048682

In [59]:
search_params = {'n_components': [2, 5, 7, 10, 15, 20, 25, 30], 'learning_decay': [.5, .7, .9]}

# Init the Model
lda = LDA()

# Init Grid Search Class
model = GridSearchCV(lda, param_grid=search_params)

# Do the Grid Search
model.fit(A)

GridSearchCV(cv=None, error_score=nan,
             estimator=LatentDirichletAllocation(batch_size=128,
                                                 doc_topic_prior=None,
                                                 evaluate_every=-1,
                                                 learning_decay=0.7,
                                                 learning_method='batch',
                                                 learning_offset=10.0,
                                                 max_doc_update_iter=100,
                                                 max_iter=10,
                                                 mean_change_tol=0.001,
                                                 n_components=10, n_jobs=None,
                                                 perp_tol=0.1,
                                                 random_state=None,
                                                 topic_word_prior=None,
                                                 total_samples=1000000.0,
                                                 verbose=0),
             iid='deprecated', n_jobs=None,
             param_grid={'learning_decay': [0.5, 0.7, 0.9],
                         'n_components': [2, 5, 7, 10, 15, 20, 25, 30]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [60]:
best_lda_model = model.best_estimator_

# Model Parameters
print("Best Model's Params: ", model.best_params_)

# Log Likelihood Score
print("Best Log Likelihood Score: ", model.best_score_)

# Perplexity
print("Model Perplexity: ", best_lda_model.perplexity(A))

Best Model's Params:  {'learning_decay': 0.5, 'n_components': 5}
Best Log Likelihood Score:  -16895.18026072038
Model Perplexity:  23.726334615567012